### ISSUE TITLE
Error detected while processing function latexfmt#FormatLines:

### ISSUE THREAD

**Issue by ghost** [engeljh/vim-latexfmt#1] opened 2020-03-26 05:44 UTC
I get the following error while I try to format current paragraph.
```vim
Error detected while processing function latexfmt#FormatLines:
E20: Mark not set
```
I see that it is formatting the paragraph, but after this error, the cursor ends up at the beginning of the file.
Also the plugin introduces a significant lag in the navigation.

**Comment by engeljh** [comment] 2020-03-26 13:46
That's interesting; I've seen neither problem.  Would you mind sending me your file, or an example that exhibits the same problem(s)?

**Comment by engeljh** [comment] 2020-03-26 13:47
That's interesting; I've seen neither problem. Would you mind sending me your file, or an example that exhibits the same problem(s)?

________________________________

**Comment by ghost** [comment] 2020-03-26 17:56
Okay I will do that in some time. By the way I am using `neovim`, I am guessing that will not be a problem.

**Comment by engeljh** [comment] 2020-03-26 20:57
It works fine on neovim for me.

________________________________

**Comment by ghost** [comment] 2020-03-27 04:47
It's weird. I have vimtex installed and the error comes only when both of them are enabled. If I disable vimtex it nicely formats my text as it should. Here's my configurations for both plugins
```vim
    Plug 'lervag/vimtex', {'for': 'tex'}
    let g:tex_flavor='latex'
    let g:vimtex_quickfix_mode=0
    let g:vimtex_quickfix_latexlog = {'default' : 0}
    set conceallevel=1
    let g:tex_conceal='bmg'
    " Indent settings
    let g:vimtex_indent_enabled=1
    let g:vimtex_indent_bib_enabled=1
    let g:vimtex_format_enabled=1
    " Fold settings
    let g:vimtex_fold_enabled=1
    let g:vimtex_fold_manual=1
    let g:vimtex_fold_types={
                \ 'preamble' : {'enabled' : 1},
                \ 'sections' : { 'sections' : ['chapter', 'section', 'subsection']},
                \ 'envs'     : { 'enabled' : 1, 'whitelist' : ['comment'],},
                \}
    set fillchars=fold:\ 

    Plug 'engeljh/vim-latexfmt', {'for': 'tex'}
    nmap <unique><silent> <leader>lf <Plug>latexfmt_format
    let g:latexfmt_no_join_any=  [ '%', '\begin', '\end', '\vspace', '\noindent', '\caption' ]
    let g:latexfmt_no_join_prev= [ '\item', '\label' ]
    let g:latexfmt_verbatim_envs=[ '\align' ]
```

**Comment by ghost** [comment] 2020-03-27 04:57
Consider the following text
```latex
\documentclass[]{report}

\begin{document}
This is a simple text I want to format. It is everywhere over the line and I would expect it to be nice. Here's some math $\alpha+\beta = \gamma \frac{\sigma}{\sqrt{1.2}}$.
\end{document}
```
The error doesn't appear when I am on the `\begin` or `\end` lines and I get a nicely formatted output
```latex

\begin{document}
This is a simple text I want to format. It is everywhere over the line and I
would expect it to be nice. Here's some math $\alpha+\beta = \gamma
\frac{\sigma}{\sqrt{1.2}}$.
\end{document}
```
 Only when I try to format while I am anywhere on the text in between the error pops up. And as I said in the earlier comment it only happens in combination with vimtex.

**Comment by engeljh** [comment] 2020-03-27 14:48
The plugin seems to clash with vimtex when vimtex_format_enabled is set.  Can you check to see whether you still encounter problems when you comment out the line where you set that variable?

________________________________

**Comment by ghost** [comment] 2020-03-27 16:16
Yes, the error goes away when I disable vimtex formatting. Should have thought through that. I also found out that the lag I mentioned is present only if I enable vimtex folding. If I comment out fold settings, the lag also goes away. Any clue why?

**Comment by engeljh** [comment] 2020-03-27 18:54
No clue.  The code is very simple.  I will post a question for the vimtex guy and let you know.

________________________________

**Comment by engeljh** [comment] 2020-03-27 19:17
Can you please give me the smallest possible .vimrc file that causes the error in the tex file you provided?  Thanks.

________________________________

**Comment by lervag** [comment] 2020-03-28 22:53
With `g:vimtex_format_enabled` vimtex sets the `formatexpr` which changes how `gq` works. `latexfmt` uses `gq`, and so naturally, there is a clash. Perhaps you should temporarily reset `foldexpr` while executing the formatting function? Or use `gw` instead of `gq`?

**Comment by lervag** [comment] 2020-03-28 23:00
> Yes, the error goes away when I disable vimtex formatting. Should have thought through that. I also found out that the lag I mentioned is present only if I enable vimtex folding. If I comment out fold settings, the lag also goes away. Any clue why?

Try to add `let g:vimtex_fold_manual = 1`; also, please read `:help vimtex-folding`. A better option might be to install the FastFold plugin.

**Comment by engeljh** [comment] 2020-03-29 02:30
I'll look at these  things; thank you.

**Comment by engeljh** [comment] 2020-03-29 04:01
I changed gq to gw, which seems to eliminate the error.  Oponkork, could you try doing
`let g:vimtex_fold_manual = 1` and seeing whether that eliminates the lag?

**Comment by ghost** [comment] 2020-03-29 17:14
@engeljh @lervag
Sorry guys, I am bit late to reply, First of all changing `gq` to `gw` gets rid of the error, so I am happy about that. Thanks a lot to you both.

About the lag, here's what I have found out. Here's the minimal `init.vim` to reproduce lag.
```vim
" Minimal vimrc for debugging purposes

filetype indent plugin on
syntax on
set hidden
set wildmenu
set showcmd
set number

call plug#begin('~/.local/share/nvim/plugged')

Plug 'machakann/vim-sandwich'

Plug 'lervag/vimtex', {'for': 'tex'}
let g:tex_flavor='latex'
let g:vimtex_fold_enabled=1
let g:vimtex_fold_manual=1
set fillchars=fold:\ 

Plug 'engeljh/vim-latexfmt', {'for': 'tex'}
nmap <unique><silent> <leader>lf <Plug>latexfmt_format
call plug#end()
```
And here is so far what I have figured out.
- You need all three of the plugins i.e. `vim-sandwich`, `vimtex` and `vim-latexfmt` to produce the lag.
- If I don't enable any one of the three plugins the lag goes away.
- You also need to enable `vimtex-folding` and set fold method to manual, otherwise there's no lag.

I am attaching the first [tex file ](https://github.com/engeljh/vim-latexfmt/files/4399335/coldinhere.txt) I found on astrophysics arxiv which shows me significant lag. With this minimal `init.vim` just open the tex file and try to go down by pressing `j`, you should see the lag.

P.S. please change the file extension to `.tex`.

**Comment by lervag** [comment] 2020-03-29 20:37
> I am attaching the first [tex file ](https://github.com/engeljh/vim-latexfmt/files/4399335/coldinhere.txt) I found on astrophysics arxiv which shows me significant lag. With this minimal `init.vim` just open the tex file and try to go down by pressing `j`, you should see the lag.

I'll look into it. But considering it requires three plugins to reproduce, I will "ignore" it if I don't immediately see what is causing the problem. If so, you are of course invited to open an issue on vimtex if you can further pinpoint the problem.

**Comment by lervag** [comment] 2020-03-29 21:32
The lag seems to be related to the `{'for': 'tex'}` specifiers for vim-plug. I don't know why. But these should not be necessary. Vimtex is a filetype plugin, so it only loads for `tex` files already. vim-latexfmt _should_ be a filetype plugin, and @engeljh should really consider to update. But he already did add an option `latexfmt_tex_only` that you could use. That is not so smart, since it may prevent the plugin from loading properly. Still, it is a very small plugin that does not have any clear side effects, so the `{'for': 'tex'}` really doesn't matter much.

**Comment by engeljh** [comment] 2020-03-29 22:51
Well, engeljh will make latexfmt a filetype plugin.  The functionality for non-tex files is minimal.

________________________________

**Comment by engeljh** [comment] 2020-03-30 20:14
I checked this with the plugins installed the native vim way and didn't observe any lag, so I'm going to close the issue.  I also rearranged things so that LaTeXfmt is a filetype plugin; that meant removing functionality for non-tex files.  Let me know if you have any more issues.

**Closed as completed by engeljh** 2020-03-30 20:14 UTC

**Comment by ghost** [comment] 2020-03-31 03:29
Thanks a lot @engeljh and @lervag for your support.
I updated `vim-latexfmt` and now I don't see any lag even with `{'for' : 'tex'}` specifier.
I wonder if it has anything to do with `vim-latexfmt` now being a filetype plugin.

Anyway, thanks once again! The error is gone, the lag is gone and I am happy.

**Comment by lervag** [comment] 2020-03-31 06:23
No problem, happy to help :)

**Comment by engeljh** [comment] 2020-03-31 13:39
My pleasure as well.


________________________________
